/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PowerRouteImport } from './routes/power'
import { Route as LocalizationRouteImport } from './routes/localization'
import { Route as IndexRouteImport } from './routes/index'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRoute = PowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizationRoute = LocalizationRouteImport.update({
  id: '/localization',
  path: '/localization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/localization': typeof LocalizationRoute
  '/power': typeof PowerRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/localization': typeof LocalizationRoute
  '/power': typeof PowerRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/localization': typeof LocalizationRoute
  '/power': typeof PowerRoute
  '/roadmap': typeof RoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/localization' | '/power' | '/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/localization' | '/power' | '/roadmap'
  id: '__root__' | '/' | '/localization' | '/power' | '/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocalizationRoute: typeof LocalizationRoute
  PowerRoute: typeof PowerRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localization': {
      id: '/localization'
      path: '/localization'
      fullPath: '/localization'
      preLoaderRoute: typeof LocalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocalizationRoute: LocalizationRoute,
  PowerRoute: PowerRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
